### ISSUE TITLE
2.1 / 2.2 / 2.3 ?

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFUid#1]
@esteele I see that the default branch in our fork is using branch 2.1, while 5.0 is pinning 2.2.1 and (zopefoundation) upstream is using 2.3.

Is there any specific reason to use 2.1 branch as the default one?

**Comment by gforcada** [comment]
A quick test shows that 2.1 is totally broken with current buildout.coredev (Plone 5). 2.2 branch works fine.

**Comment by esteele** [comment]
Yeah. We want 2.2. CMF 2.3 has a bunch of stuff that's incompatible and I'm not sure there's anything new we'd want from it.

**Comment by esteele** [comment]
I don't know why that's the default. I didn't specify one after forking.

**Comment by gforcada** [comment]
No idea either, I will change it to 2.2 then. Thanks!
